Adds Min's article on kubernetes
thefrontside/frontside.io pull request #118
Opened 2021-01-29 17:18 UTC by jorgelainfiesta

## Motivation

Min wrote this article in December

## Approach

We opted for a very lightweight generalistic style for this article

2021-01-29 17:28 UTC, minkimcello commented
We should add @taras. He wrote the important parts. And also I didn't know you guys would keep the title. 😆

2021-01-30 09:24 UTC, jorgelainfiesta commented
It's your article, I thought that title was like a personality touch that you added, what should it be? (make it water related, I won't make another image for it lol)

Let's not get Taras involved. If you're insecure about some point you can ask Elrick, he wrote an article on Kubernetes earlier on.

2021-02-02 16:01 UTC, minkimcello requested changes

2021-02-02 16:01 UTC, minkimcello commented on src/pages/blog/2021-01-29-kubernetes-wet-your-toes.md
> +Kubernetes changes all that. It makes understanding these platforms approachable and manageable, allowing frontend developers to learn all about them fairly quickly. The architecture of Kubernetes an
> The architecture of Kubernetes and the approach that the Kubernetes community is taking towards building it continuously lowers the barrier

Can we reword this to something like `The architecture of Kubernetes and the approach that the community is taking towards building Kubernetes`

2021-02-02 16:01 UTC, minkimcello commented on src/pages/blog/2021-01-29-kubernetes-wet-your-toes.md
> +```$ brew install ubuntu/microk8s/microk8s```
The back ticks need to be on their own line

2021-02-02 16:01 UTC, minkimcello commented on src/pages/blog/2021-01-29-kubernetes-wet-your-toes.md
> +What we’re seeing here are the pods from the service we deployed. We’ll be returning to this page very shortly, but for practice if you want to navigate to the list of deployments, press ‘:’ and type
Were these meant to be back ticks?

2021-02-03 12:59 UTC, minkimcello approved these changes
👍

2021-02-03 13:31 UTC, merged