Adds Paul'st article about auth0 simulator and nav option
thefrontside/frontside.io pull request #178
Opened 2022-01-13 12:13 UTC by jorgelainfiesta

## Motivation

Announce Auth0 simulator

## Approach

Paul wrote article, I edited and proofed with Olson

2022-01-13 13:13 UTC, dagda1 requested changes
Nice work!  Just one update to a code example

2022-01-13 13:13 UTC, dagda1 commented on src/blog/2022-01-13-auth0-simulator.md
> +<Button onClick={() => loginWithRedirect()}>  Log in   </Button>;
```suggestion
import { useAuth0 } from "@auth0/auth0-react";

const LoginButton = () => {
  const { loginWithRedirect } = useAuth0();

  return <button onClick={() => loginWithRedirect()}>Log In</button>;
};
```

2022-01-14 08:26 UTC, jorgelainfiesta commented
@dagda1 I committed your change, thanks! can you do a final check so we can publish it? thanks!

2022-01-14 10:13 UTC, dagda1 commented
> @dagda1 I committed your change, thanks! can you do a final check so we can publish it? thanks!

I think it is good to go.  When are you thinking of publishing this?  I have a couple of PRs that I would like to get merged in the auth0 simulator.

It would be good to have those merged in case anyone feels inspired to give it a go after reading the blog post.

2022-01-14 16:07 UTC, jorgelainfiesta commented
I can publish it whenever you feel it's ready

2022-01-19 09:22 UTC, cowboyd reviewed
Looks great! some minor comments inline.

2022-01-19 09:22 UTC, cowboyd commented on src/blog/2022-01-13-auth0-simulator.md
> +```JSON
It looks like this is not valid JSON. 

I think there are quotes missing around the "domain" key.

2022-01-19 09:22 UTC, cowboyd commented on src/blog/2022-01-13-auth0-simulator.md
> +      .given()
`given()` without any context doesn't really read well.

```ts
given({
  email: 'bob@gmail.com'
});
```

makes sense, but just
```ts
given()
```
is a bit weird. Not sure what to do? Thoughts?

2022-01-19 09:22 UTC, cowboyd commented on src/blog/2022-01-13-auth0-simulator.md
> +A third solution is creating phony Auth0 accounts for different environments, but that too is a maintainability nightmare. The accounts on each environment must now be kept in sync, which is unlikely
Are we underselling the pain associated with this setup here? Basically, you have a single "fake" online auth0 tenant for testing, which is a global dumping ground for anybody that happens to be doing testing in your organization at any given moment. There are so many cons to this very common approach that I feel like we should say them out loud:

1. You are at the mercy of Auth0 to provision you each testing tenant
1. You cannot test if Auth0 is unavailable or your are developing "behind the firewall"
1. You are still subject to rate limits of however many testers happen to be using it. When that rate limit is breached, _all_ tests in your whole organization are blocked.
3. The test accounts share state with everyone who happens to be running a test _at the same time_, and so every test has a hidden dependency on _every other test_.

2022-01-19 14:17 UTC, jorgelainfiesta commented on src/blog/2022-01-13-auth0-simulator.md
> +      .given()
We can add the email as you suggest, I don't have any strong opinion

2022-01-24 12:52 UTC, cowboyd approved these changes

2022-01-24 14:08 UTC, dagda1 approved these changes
👍

2022-01-24 17:04 UTC, taras commented
@jorgelainfiesta @dagda1 the link in the conclusion of the blog post links to simulacrum repo. Should it point to https://github.com/thefrontside/simulacrum/tree/v0/packages/auth0?

2022-01-24 17:05 UTC, dagda1 commented
> @jorgelainfiesta @dagda1 the link in the conclusion of the blog post links to simulacrum repo. Should it point to https://github.com/thefrontside/simulacrum/tree/v0/packages/auth0?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/25770f5dc358090ed62ca25b3bf7be20f97001d07adba549675eb8300bb55f27/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f376439323331663933393137306332316637333164613530363332353436636138633837646461636162646633306165356563333933323839376464663830632f74686566726f6e74736964652f73696d756c616372756d"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[simulacrum/packages/auth0 at v0 · thefrontside/simulacrum](https://github.com/thefrontside/simulacrum)**A simulation platform for use during testing, during development and for high-fidelity application previews - simulacrum/packages/auth0 at v0 · thefrontside/simulacrum

@taras yes, good spot, it should point to the auth0 package.

2022-01-24 19:09 UTC, merged