Add part 2 blog post ingestion testing
thefrontside/frontside.io pull request #202
Opened 2022-04-26 17:29 UTC by JavierLainparty

Add blog post

2022-04-26 19:17 UTC, taras commented
@JavierLainparty I haven't had a chance to read it yet, but in the mean time - can you please find a way to make this image smaller 
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/74687/165375479-72479b20-35b2-4da2-8700-465612cd6e4e.png">


@cowboyd we can generate SVGs from terminal output. I think we need to do this to make it easier to see Jest output.

2022-04-27 07:47 UTC, cowboyd commented
@taras Yeah, I'll look into recording those as SVG animations. It might actually add a bit of pep to the post, looks like https://github.com/nbedos/termtosvg is good (although no longer maintained)

@JavierLainparty Any chance you can update your GitHub profile to contain your avatar? You're so much more than a space invader :) 👾

2022-04-27 15:40 UTC, taras requested changes
We need to fix the image size and improve the terminal output.

2022-04-27 15:40 UTC, taras commented on src/blog/2022-04-26-ingestion-tests-in-backstage-part-2.md
> +In this article we’ll demonstrate this by refactoring in order to upgrade a Backstage server from the legacy LDAP org processor to the new LDAP entity provider – all without changing a single line of
This is duplicated.

2022-04-27 15:41 UTC, taras commented
> @taras Yeah, I'll look into recording those as SVG animations. It might actually add a bit of pep to the post, looks like https://github.com/nbedos/termtosvg is good (although no longer maintained)

That would be good

2022-04-29 13:55 UTC, cowboyd commented
@JavierLainparty Here is the raw asciinema cast of the tests running https://asciinema.org/a/491054

2022-04-29 18:38 UTC, taras commented
@JavierLainparty let me know if you'd like help getting this file embedded.

2022-05-04 17:06 UTC, taras commented
@cowboyd what about something like this to generate HTML from the terminal? https://github.com/masukomi/oho

2022-05-06 11:53 UTC, cowboyd commented
@taras I couldn't get that tool to work on my `m1` Mac. I can try compiling from source.

```
dyld[81365]: Library not loaded: /opt/homebrew/Cellar/pcre/8.45/lib/libpcre.1.dylib
  Referenced from: /opt/homebrew/Cellar/oho/1.3.5/bin/oho
```

2022-05-06 11:54 UTC, taras commented
Oh right, that sucks

2022-05-06 11:59 UTC, cowboyd commented
Looks like building from source is a no-go either as it throws an exception..... feels like this is harder than it should be

2022-05-06 12:00 UTC, cowboyd commented
Another option would be to use this in playwright to render the terminal, and then get back the HTML https://github.com/xtermjs/xterm.js/ 🤷🏻 

<blockquote><img src="https://opengraph.githubassets.com/4c079df9e85a2f2d076b007372684e833ff2808476cf19e18629c97c64923c96/xtermjs/xterm.js" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/xtermjs/xterm.js">GitHub - xtermjs/xterm.js: A terminal for the web</a></strong></div><div>A terminal for the web. Contribute to xtermjs/xterm.js development by creating an account on GitHub.</div></blockquote>

2022-05-06 12:36 UTC, cowboyd commented
Ok, we'll see if this works. I was able to install this, and capture the raw terminal output from Jest in both cases.

 https://github.com/buildkite/terminal-to-html


Here is the gist that contains `pass.html` and `fail.html` along with the raw terminal output that generated them.

2022-05-06 12:39 UTC, cowboyd commented
@JavierLainparty We can either use an `iframe` on this, or we can try and massage the html and only take the elements / styles that we need.

2022-11-30 22:48 UTC, cowboyd commented
Superseded by #223

2022-11-30 22:48 UTC, closed without merging