Adds article about Mirage serializers
thefrontside/frontside.io pull request #96
Opened 2020-08-31 19:34 UTC by jorgelainfiesta

## Motivation

Min did an extensive research on Mirage serializers 

## Approach

Min provided me with a draft, then I poked his brain for days until this piece finally its final, extensive, shape.

2020-08-31 21:08 UTC, minkimcello requested changes

2020-08-31 21:08 UTC, minkimcello commented on src/pages/blog/2020-08-31-mirage-serializers.md
> +The Active Model Serializer changes the caps to be under_scored no matter how the original model name was configured. As you can see in the example, the attribute names that were inconsistently cased
https://deploy-preview-96--frontside.netlify.app/blog/2020-08-31-mirage-serializers/#field-names-format-under_scored

i think we need to escape the underscore

2020-08-31 21:08 UTC, minkimcello commented on src/pages/blog/2020-08-31-mirage-serializers.md
> +The Active Model Serializer changes the caps to be under_scored no matter how the original model name was configured. As you can see in the example, the attribute names that were inconsistently cased
i was reading it going "whoa, this is dramatic" then thought maybe it wasn't intentional

2020-08-31 21:09 UTC, minkimcello commented
I found two small errors ☝️.  Otherwise it looks great! 🙏

2020-09-01 07:43 UTC, jorgelainfiesta commented on src/pages/blog/2020-08-31-mirage-serializers.md
> +The Active Model Serializer changes the caps to be under_scored no matter how the original model name was configured. As you can see in the example, the attribute names that were inconsistently cased
haha good catch! fixing it now

2020-09-01 13:36 UTC, minkimcello approved these changes

2020-09-01 15:06 UTC, cherewaty approved these changes
👏 👏 👏

2020-09-01 16:12 UTC, cowboyd commented
I love it! I have only two suggestions

1. we link to the simulation article at the end as "related", but I think we could make an actual hyperlink to it when we say "we prefer to think of this as simulation"
2. Can we give mirage graphql honorable mention at the end as something that let's you not have to worry about serializers ever?

2020-09-02 07:21 UTC, jorgelainfiesta commented
Wow I didn't even know Mirage GraphQL existed... 🤯

2020-09-02 07:49 UTC, merged